### ISSUE TITLE
How to install on Nvidia Shield ?

### ISSUE THREAD

**Issue by kevindesousa** [ledge74/HelloHue.bundle#17]

**Comment by sschadwick** [comment]
Did you attempt to install this? Is your ShieldTV rooted? Did you run into any issues? What error messages did you get?

**Comment by ledge74** [comment]
Unfortunately it seems that it is not officially possible : https://support.plex.tv/articles/221099648-limitations-when-running-plex-media-server-on-nvidia-shield/
