### ISSUE TITLE
Feature request: Respect user privacy and stop spying on the user

### ISSUE THREAD

**Issue by wridgers** [ledge74/HelloHue.bundle#20]
https://github.com/ledge74/HelloHue.bundle/blob/37ea90faf2fdf8d3badddfb5466173329e8e6122/Contents/Code/__init__.py#L74-L85

Seems like this plugin is spying on the user. Very sneaky behaviour.

Please don't do this.

**Comment by ledge74** [comment]
Please don't make false accusations, there is an option to disable tracking, just use it.

![image](https://user-images.githubusercontent.com/6603944/41672051-33538e1e-74b9-11e8-8bd4-2388f35af0be.png)

**Comment by wridgers** [comment]
- No mention of tracking in the README.
  - Tracking is on by default.

How do I use HelloHue without ever having it spy on me? I have to run it (with tracking!) to turn tracking off.

The default value should be off. HelloHue should ask for permission.
