### ISSUE TITLE
Unable to find bridge

### ISSUE THREAD

**Issue by Kallb123** [ledge74/HelloHue.bundle#8]
I follow the instructions: press bridge button and then click the link, but all I see afterwards is "This channel is not responding." 

I can go back and refresh and the plug in works again and if I go to advanced and reboot it does that, but it still says "Press button on your bridge and click to connect". 

Both devices are on the same network. The bridge has paired fine with many other apps. The plex server is behind a firewall, is there a specific port used for pairing maybe?

**Comment by rtho782** [comment]
Same issue for me.

PMS version 1.2.0.3167, if relevant this is the latest PlexDVR release.
HelloHue 1.1.8.4

I push the button on the hue hub then click connect on plex, and get a spinning circle before "This channel is not responding"
[Plex Media Server Logs_2017-02-04_21-00-46.zip](https://github.com/ledge74/HelloHue.bundle/files/752562/Plex.Media.Server.Logs_2017-02-04_21-00-46.zip)

**Comment by Kallb123** [comment]
@rtho782 that's the same description as what I'm facing. Thanks for posting the log. I can try and post mine if it would help. I'm on PMS version 1.3.3.3148. Not using PlexDVR, it might be a PlexPass version but not sure now.

**Comment by rtho782** [comment]
@Kallb123 I've actually solved mine now, it was my own idiotic fault - I had set the wrong IP for the Hue Hub in the settings. Must have been a typo as it wasn't even the right subnet, I'm an idiot etc!!!

**Comment by Kallb123** [comment]
Oh crap, what settings? The instructions don't mention changing any IP settings do they?

**Comment by Kallb123** [comment]
So I was being stupid, I've properly read the steps and it does tell you to change settings.

**Comment by rtho782** [comment]
Well this is an embarrassing thread for both of us :3
